version: "3.8"
services:
  xahau-docproof-db:
    image: mongo:8.0.1-rc0-noble
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-securepassword}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-xahau-docproof}
    profiles: 
      - mongodb
    volumes:
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo-data:/data/db

  xahau-docproof-api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_URI=${MONGO_URI:-mongodb://xahau-docproof-db:27017/xahau-docproof}
    command: ["npm", "run", "serve"]
    volumes:
      - storage-data:/storage

  xahau-docproof-xapp:
    build:
      context: ./xapp/
      dockerfile: Dockerfile
    ports:
      - "${XAPP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=${API_URL:-http://xahau-docproof-api:3001/api/}
    command: ["npm", "run", "dev"]

volumes:
  storage-data:
  mongo-data:

networks:
  default:
    name: xahau-docproof-network
