version: "3.8"
services:
  xahau-docproof-db:
    image: mongo:8.0.1-rc0-noble
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-securepassword}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-xahau-docproof}
    profiles: 
      - mongodb
    volumes:
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo-data:/data/db

  xahau-docproof-api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "${OUTSIDE_API_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_URI=${MONGO_URI:-mongodb://xahau-docproof-db:27017/xahau-docproof}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["npm", "run", "serve"]
    volumes:
      - storage-data:/storage

  xahau-docproof-xapp:
    build:
      context: ./xapp/
      dockerfile: Dockerfile
    ports:
      - "${OUTSIDE_XAPP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://xahau-docproof-api:3001/api/}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: bash -c "npm install --omit=dev && npm run build && npm run start"

networks:
  default:
    name: xahau-docproof-network
